//! Pasting into the previously focused app, and what the clipboard history
//! needs to know about the clipboard and the app that filled it.
//!
//! The OS-specific parts (remembering the foreground window, refocusing it,
//! synthesizing the paste keystroke, reading the clipboard's "secret" markers)
//! live in the `windows`, `macos` and `linux` modules. This module holds the
//! shared types and the order of operations, which is the same everywhere.

use std::thread::sleep;
use std::time::Duration;

use sevak_core::ClipContent;

use crate::clipboard;
use crate::error::Result;

/// The application that owns a window: what the clipboard history shows as the
/// source of a copy and what `[clipboard] ignore_apps` is matched against.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ForegroundApp {
    /// Display name: the program name on Windows and Linux, the app name on macOS.
    pub name: String,
    /// Other names the app answers to (executable file name, bundle id,
    /// `WM_CLASS`).
    pub identifiers: Vec<String>,
}

impl ForegroundApp {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            identifiers: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_identifier(mut self, identifier: impl Into<String>) -> Self {
        let identifier = identifier.into();
        if !identifier.is_empty() && identifier != self.name {
            self.identifiers.push(identifier);
        }
        self
    }

    /// True if `pattern` names this app: case-insensitive, and `.exe` / `.app`
    /// suffixes do not matter (`keepassxc`, `KeePassXC.exe` and `KeePassXC`
    /// are the same app).
    pub fn matches(&self, pattern: &str) -> bool {
        let pattern = normalize_app_name(pattern);
        !pattern.is_empty()
            && std::iter::once(&self.name)
                .chain(&self.identifiers)
                .any(|name| normalize_app_name(name) == pattern)
    }

    pub fn matches_any(&self, patterns: &[String]) -> bool {
        patterns.iter().any(|pattern| self.matches(pattern))
    }
}

fn normalize_app_name(name: &str) -> String {
    let lower = name.trim().to_lowercase();
    for suffix in [".exe", ".app"] {
        if let Some(stripped) = lower.strip_suffix(suffix) {
            return stripped.to_owned();
        }
    }
    lower
}

/// Whether text can be pasted into another app on this system right now.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PasteSupport {
    Available,
    /// Only copying works; the reason is meant for the user.
    CopyOnly(String),
}

impl PasteSupport {
    pub fn is_available(&self) -> bool {
        matches!(self, Self::Available)
    }
}

/// What [`crate::PlatformProvider::paste_text`] managed to do. The text is on
/// the clipboard either way.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PasteOutcome {
    Pasted,
    CopiedOnly(String),
}

/// The clipboard as the history sees it.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ClipboardRead {
    /// The text on the clipboard; `None` if it holds something else (or nothing).
    pub text: Option<String>,
    /// The app that put it there asked for it not to be recorded (password
    /// managers do). `text` is `None` in that case: it is never read.
    pub sensitive: bool,
}

/// Pasteboard types (the `nspasteboard.org` convention) with which apps say
/// "this is a password, a one-time code or generated data: do not record it".
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
const SECRET_PASTEBOARD_TYPES: [&str; 3] = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// True if any of the pasteboard's `types` marks its content as secret.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub(crate) fn pasteboard_marks_secret(types: &[String]) -> bool {
    types
        .iter()
        .any(|ty| SECRET_PASTEBOARD_TYPES.contains(&ty.as_str()))
}

/// Reason shown where pasting is unavailable for lack of any implementation.
pub const UNSUPPORTED_REASON: &str = "Pasting into other apps is not supported here";

/// Gap after the target window got focus, so it is ready for the keystroke.
const FOCUS_SETTLE: Duration = Duration::from_millis(40);
/// Gap after the keystroke before the old clipboard is put back, so the target
/// has read the pasted text (slow apps read it asynchronously).
const RESTORE_DELAY: Duration = Duration::from_millis(300);

/// The OS half of a paste.
pub(crate) trait PasteDriver {
    /// Brings the remembered window back to the foreground. `Err` carries a
    /// message for the user when that is not possible.
    fn focus_previous(&self) -> std::result::Result<(), String>;
    /// Sends Ctrl+V / Cmd+V to the focused window.
    fn press_paste(&self) -> Result<()>;
}

/// What a paste puts on the clipboard first.
#[derive(Debug, Clone, Copy)]
pub(crate) enum PasteContent<'a> {
    Text(&'a str),
    /// An image or files (see [`ClipContent`]).
    Clip(&'a ClipContent),
}

impl PasteContent<'_> {
    /// Puts the content on the clipboard without pasting it (where pasting is
    /// not possible).
    #[cfg_attr(windows, allow(dead_code))]
    pub(crate) fn copy(self) -> Result<()> {
        match self {
            Self::Text(text) => clipboard::set_text(text),
            Self::Clip(content) => clipboard::set_clip(content, false),
        }
    }
}

/// The clipboard operations a paste needs; a trait so the order of operations
/// can be tested without touching the real clipboard.
pub(crate) trait PasteClipboard {
    /// The clipboard's text, to put back afterwards. (An image or file list
    /// that was there is not restored: only text is.)
    fn get_text(&self) -> Option<String>;
    /// Replaces the clipboard's content, asking the OS to keep it out of its
    /// own history.
    fn set_private(&self, content: PasteContent<'_>) -> Result<()>;
}

pub(crate) struct SystemClipboard;

impl PasteClipboard for SystemClipboard {
    fn get_text(&self) -> Option<String> {
        clipboard::get_text().ok().flatten()
    }

    fn set_private(&self, content: PasteContent<'_>) -> Result<()> {
        match content {
            PasteContent::Text(text) => clipboard::set_text_private(text),
            PasteContent::Clip(content) => clipboard::set_clip(content, true),
        }
    }
}

/// Copies `content`, refocuses the previous window and presses paste.
///
/// Only a failure to copy is an error. If the previous window cannot be
/// refocused or the keystroke cannot be sent, the content stays on the
/// clipboard and the outcome says so, so the user can paste by hand.
pub(crate) fn paste(
    content: PasteContent<'_>,
    restore_clipboard: bool,
    clipboard: &dyn PasteClipboard,
    driver: &dyn PasteDriver,
    delays: bool,
) -> Result<PasteOutcome> {
    // Read first: setting the content replaces it.
    let previous = restore_clipboard.then(|| clipboard.get_text()).flatten();

    clipboard.set_private(content)?;

    if let Err(reason) = driver.focus_previous() {
        return Ok(PasteOutcome::CopiedOnly(reason));
    }
    if delays {
        sleep(FOCUS_SETTLE);
    }
    if let Err(err) = driver.press_paste() {
        tracing::warn!("could not send the paste keystroke: {err}");
        return Ok(PasteOutcome::CopiedOnly(format!(
            "Could not press paste ({err}); it is on the clipboard"
        )));
    }

    if let Some(previous) = previous {
        if delays {
            sleep(RESTORE_DELAY);
        }
        if let Err(err) = clipboard.set_private(PasteContent::Text(&previous)) {
            tracing::warn!("could not restore the clipboard: {err}");
        }
    }
    Ok(PasteOutcome::Pasted)
}

#[cfg(test)]
mod tests {
    use std::cell::RefCell;

    use super::*;

    #[derive(Default)]
    struct Fake {
        clipboard: RefCell<Option<String>>,
        log: RefCell<Vec<String>>,
        focus_error: Option<String>,
        key_error: bool,
    }

    impl PasteClipboard for Fake {
        fn get_text(&self) -> Option<String> {
            self.clipboard.borrow().clone()
        }
        fn set_private(&self, content: PasteContent<'_>) -> Result<()> {
            match content {
                PasteContent::Text(text) => {
                    self.log.borrow_mut().push(format!("set {text}"));
                    *self.clipboard.borrow_mut() = Some(text.to_owned());
                }
                PasteContent::Clip(clip) => {
                    self.log.borrow_mut().push(format!("set {clip:?}"));
                    // An image or file list replaces the text.
                    *self.clipboard.borrow_mut() = None;
                }
            }
            Ok(())
        }
    }

    impl PasteDriver for Fake {
        fn focus_previous(&self) -> std::result::Result<(), String> {
            self.log.borrow_mut().push("focus".into());
            self.focus_error.clone().map_or(Ok(()), Err)
        }
        fn press_paste(&self) -> Result<()> {
            self.log.borrow_mut().push("paste".into());
            if self.key_error {
                Err(crate::PlatformError::Unsupported("keys"))
            } else {
                Ok(())
            }
        }
    }

    fn run(fake: &Fake, restore: bool) -> PasteOutcome {
        paste(
            PasteContent::Text("new"),
            restore,
            fake as &dyn PasteClipboard,
            fake as &dyn PasteDriver,
            false,
        )
        .unwrap()
    }

    #[test]
    fn copies_then_focuses_then_pastes() {
        let fake = Fake::default();
        assert_eq!(run(&fake, false), PasteOutcome::Pasted);
        assert_eq!(*fake.log.borrow(), ["set new", "focus", "paste"]);
    }

    #[test]
    fn restores_the_previous_text_after_pasting() {
        let fake = Fake::default();
        *fake.clipboard.borrow_mut() = Some("old".into());
        assert_eq!(run(&fake, true), PasteOutcome::Pasted);
        assert_eq!(*fake.log.borrow(), ["set new", "focus", "paste", "set old"]);
        assert_eq!(fake.clipboard.borrow().as_deref(), Some("old"));
    }

    #[test]
    fn an_image_is_pasted_like_text_and_the_old_text_comes_back() {
        let fake = Fake::default();
        *fake.clipboard.borrow_mut() = Some("old".into());
        let clip = ClipContent::Image {
            path: "a.png".into(),
        };
        let outcome = paste(
            PasteContent::Clip(&clip),
            true,
            &fake as &dyn PasteClipboard,
            &fake as &dyn PasteDriver,
            false,
        )
        .unwrap();
        assert_eq!(outcome, PasteOutcome::Pasted);
        let log = fake.log.borrow();
        assert!(log[0].starts_with("set Image"), "{log:?}");
        assert_eq!(log[1..], ["focus", "paste", "set old"]);
    }

    #[test]
    fn does_not_touch_the_old_clipboard_unless_asked() {
        let fake = Fake::default();
        *fake.clipboard.borrow_mut() = Some("old".into());
        run(&fake, false);
        assert_eq!(fake.clipboard.borrow().as_deref(), Some("new"));
    }

    #[test]
    fn a_failed_refocus_leaves_the_text_copied() {
        let fake = Fake {
            focus_error: Some("window gone".into()),
            ..Fake::default()
        };
        assert_eq!(
            run(&fake, true),
            PasteOutcome::CopiedOnly("window gone".into())
        );
        assert_eq!(*fake.log.borrow(), ["set new", "focus"]);
        assert_eq!(fake.clipboard.borrow().as_deref(), Some("new"));
    }

    #[test]
    fn a_failed_keystroke_leaves_the_text_copied() {
        let fake = Fake {
            key_error: true,
            ..Fake::default()
        };
        *fake.clipboard.borrow_mut() = Some("old".into());
        assert!(matches!(run(&fake, true), PasteOutcome::CopiedOnly(_)));
        // The user still needs the text to paste it by hand.
        assert_eq!(fake.clipboard.borrow().as_deref(), Some("new"));
    }

    #[test]
    fn concealed_and_transient_pasteboard_types_are_secret() {
        let types = |names: &[&str]| names.iter().map(|n| (*n).to_owned()).collect::<Vec<_>>();
        assert!(pasteboard_marks_secret(&types(&[
            "public.utf8-plain-text",
            "org.nspasteboard.ConcealedType"
        ])));
        assert!(pasteboard_marks_secret(&types(&[
            "org.nspasteboard.TransientType"
        ])));
        assert!(!pasteboard_marks_secret(&types(&[
            "public.utf8-plain-text"
        ])));
        assert!(!pasteboard_marks_secret(&[]));
    }

    #[test]
    fn app_names_match_loosely() {
        let app = ForegroundApp::new("KeePassXC")
            .with_identifier("keepassxc.exe")
            .with_identifier("org.keepassxc.KeePassXC");
        assert!(app.matches("keepassxc"));
        assert!(app.matches(" KEEPASSXC.EXE "));
        assert!(app.matches("org.keepassxc.keepassxc"));
        assert!(!app.matches("keepass"));
        assert!(!app.matches(""));
        assert!(app.matches_any(&["x".into(), "KeePassXC".into()]));
        assert!(!app.matches_any(&[]));
        assert!(ForegroundApp::new("Safari").matches("safari.app"));
    }
}
