//! Latency of `SearchEngine::query` end to end with the default built-in
//! plugins over a large mock index, and of the startup index build.
//!
//! ```sh
//! cargo bench -p sevak-plugins                 # everything
//! cargo bench -p sevak-plugins -- "query/calc" # one query
//! ```
//!
//! The data (5 000 apps, 100 000 files, 10 000 bookmarks, a 200-entry clipboard
//! history, the two example workflows) is generated by `benches/fixture`; the
//! engine warns about queries over 16 ms (`sevak_core::engine::LATENCY_BUDGET`),
//! which is the line these numbers should stay under on a developer machine.
//! `docs/testing.md` explains how to read the results.

use std::hint::black_box;
use std::time::Duration;

use criterion::{criterion_group, criterion_main, Criterion};

#[path = "fixture/mod.rs"]
mod fixture;

use fixture::{Fixture, Sizes, QUERIES};

fn queries(c: &mut Criterion) {
    let fixture = Fixture::ready(Sizes::LARGE);
    let mut group = c.benchmark_group("query");
    group.measurement_time(Duration::from_secs(4));
    for (name, input, answers) in QUERIES {
        // Every query must produce results, or the number measures nothing.
        assert!(
            !*answers || !fixture.engine.query(input).is_empty(),
            "the fixture returned nothing for {input:?} ({name})"
        );
        group.bench_function(*name, |b| b.iter(|| fixture.engine.query(black_box(input))));
    }
    group.finish();
}

fn startup(c: &mut Criterion) {
    // 20 000 real files for the files plugin to walk (the 100 000-entry index of
    // the query benchmark is injected, because creating that many files is slow).
    let sizes = Sizes {
        files: 0,
        files_on_disk: 20_000,
        ..Sizes::LARGE
    };
    let fixture = Fixture::new(sizes);
    let cold = fixture.refresh();
    println!(
        "startup: first refresh of every plugin (5 000 apps, 20 000 files walked, 10 000 bookmarks, 200 clipboard entries): {:.1} ms",
        cold.as_secs_f64() * 1000.0
    );

    let mut group = c.benchmark_group("startup");
    group.sample_size(10);
    group.measurement_time(Duration::from_secs(5));
    group.bench_function("reload index (all plugins)", |b| {
        b.iter(|| fixture.engine.refresh_all())
    });
    group.finish();
}

criterion_group!(benches, queries, startup);
criterion_main!(benches);
